import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
    providedIn: 'root'
})
export class CountriesService {

    currencies = [
        { code: 'AED', nome: 'UAE Dirham', pais: 'United Arab Emirates', isoCode: 'ae' },
        { code: 'AFN', nome: 'Afghan Afghani', pais: 'Afghanistan', isoCode: 'af' },
        { code: 'ALL', nome: 'Albanian Lek', pais: 'Albania', isoCode: 'al' },
        { code: 'AMD', nome: 'Armenian Dram', pais: 'Armenia', isoCode: 'am' },
        { code: 'AOA', nome: 'Angolan Kwanza', pais: 'Angola', isoCode: 'ao' },
        { code: 'ARS', nome: 'Argentine Peso', pais: 'Argentina', isoCode: 'ar' },
        { code: 'AUD', nome: 'Australian Dollar', pais: 'Australia', isoCode: 'au' },
        { code: 'AWG', nome: 'Aruban Florin', pais: 'Aruba', isoCode: 'aw' },
        { code: 'AZN', nome: 'Azerbaijani Manat', pais: 'Azerbaijan', isoCode: 'az' },
        { code: 'BAM', nome: 'Bosnia and Herzegovina Mark', pais: 'Bosnia and Herzegovina', isoCode: 'ba' },
        { code: 'BBD', nome: 'Barbados Dollar', pais: 'Barbados', isoCode: 'bb' },
        { code: 'BDT', nome: 'Bangladeshi Taka', pais: 'Bangladesh', isoCode: 'bd' },
        { code: 'BGN', nome: 'Bulgarian Lev', pais: 'Bulgaria', isoCode: 'bg' },
        { code: 'BHD', nome: 'Bahraini Dinar', pais: 'Bahrain', isoCode: 'bh' },
        { code: 'BIF', nome: 'Burundian Franc', pais: 'Burundi', isoCode: 'bi' },
        { code: 'BMD', nome: 'Bermudian Dollar', pais: 'Bermuda', isoCode: 'bm' },
        { code: 'BND', nome: 'Brunei Dollar', pais: 'Brunei', isoCode: 'bn' },
        { code: 'BOB', nome: 'Bolivian Boliviano', pais: 'Bolivia', isoCode: 'bo' },
        { code: 'BRL', nome: 'Brazilian Real', pais: 'Brazil', isoCode: 'br' },
        { code: 'BSD', nome: 'Bahamian Dollar', pais: 'Bahamas', isoCode: 'bs' },
        { code: 'BTN', nome: 'Bhutanese Ngultrum', pais: 'Bhutan', isoCode: 'bt' },
        { code: 'BWP', nome: 'Botswana Pula', pais: 'Botswana', isoCode: 'bw' },
        { code: 'BYN', nome: 'Belarusian Ruble', pais: 'Belarus', isoCode: 'by' },
        { code: 'BZD', nome: 'Belize Dollar', pais: 'Belize', isoCode: 'bz' },
        { code: 'CAD', nome: 'Canadian Dollar', pais: 'Canada', isoCode: 'ca' },
        { code: 'CDF', nome: 'Congolese Franc', pais: 'Democratic Republic of the Congo', isoCode: 'cd' },
        { code: 'CHF', nome: 'Swiss Franc', pais: 'Switzerland', isoCode: 'ch' },
        { code: 'CLP', nome: 'Chilean Peso', pais: 'Chile', isoCode: 'cl' },
        { code: 'CNY', nome: 'Chinese Renminbi', pais: 'China', isoCode: 'cn' },
        { code: 'COP', nome: 'Colombian Peso', pais: 'Colombia', isoCode: 'co' },
        { code: 'CRC', nome: 'Costa Rican Colon', pais: 'Costa Rica', isoCode: 'cr' },
        { code: 'CUP', nome: 'Cuban Peso', pais: 'Cuba', isoCode: 'cu' },
        { code: 'CVE', nome: 'Cape Verdean Escudo', pais: 'Cape Verde', isoCode: 'cv' },
        { code: 'CZK', nome: 'Czech Koruna', pais: 'Czech Republic', isoCode: 'cz' },
        { code: 'DJF', nome: 'Djiboutian Franc', pais: 'Djibouti', isoCode: 'dj' },
        { code: 'DKK', nome: 'Danish Krone', pais: 'Denmark', isoCode: 'dk' },
        { code: 'DOP', nome: 'Dominican Peso', pais: 'Dominican Republic', isoCode: 'do' },
        { code: 'DZD', nome: 'Algerian Dinar', pais: 'Algeria', isoCode: 'dz' },
        { code: 'EGP', nome: 'Egyptian Pound', pais: 'Egypt', isoCode: 'eg' },
        { code: 'ERN', nome: 'Eritrean Nakfa', pais: 'Eritrea', isoCode: 'er' },
        { code: 'ETB', nome: 'Ethiopian Birr', pais: 'Ethiopia', isoCode: 'et' },
        { code: 'EUR', nome: 'Euro', pais: 'European Union', isoCode: 'eu' },
        { code: 'FJD', nome: 'Fiji Dollar', pais: 'Fiji', isoCode: 'fj' },
        { code: 'FKP', nome: 'Falkland Islands Pound', pais: 'Falkland Islands', isoCode: 'fk' },
        { code: 'FOK', nome: 'Faroese Króna', pais: 'Faroe Islands', isoCode: 'fo' },
        { code: 'GBP', nome: 'Pound Sterling', pais: 'United Kingdom', isoCode: 'gb' },
        { code: 'GEL', nome: 'Georgian Lari', pais: 'Georgia', isoCode: 'ge' },
        { code: 'GGP', nome: 'Guernsey Pound', pais: 'Guernsey', isoCode: 'gg' },
        { code: 'GHS', nome: 'Ghanaian Cedi', pais: 'Ghana', isoCode: 'gh' },
        { code: 'GIP', nome: 'Gibraltar Pound', pais: 'Gibraltar', isoCode: 'gi' },
        { code: 'GMD', nome: 'Gambian Dalasi', pais: 'The Gambia', isoCode: 'gm' },
        { code: 'GNF', nome: 'Guinean Franc', pais: 'Guinea', isoCode: 'gn' },
        { code: 'GTQ', nome: 'Guatemalan Quetzal', pais: 'Guatemala', isoCode: 'gt' },
        { code: 'GYD', nome: 'Guyanese Dollar', pais: 'Guyana', isoCode: 'gy' },
        { code: 'HKD', nome: 'Hong Kong Dollar', pais: 'Hong Kong', isoCode: 'hk' },
        { code: 'HNL', nome: 'Honduran Lempira', pais: 'Honduras', isoCode: 'hn' },
        { code: 'HRK', nome: 'Croatian Kuna', pais: 'Croatia', isoCode: 'hr' },
        { code: 'HTG', nome: 'Haitian Gourde', pais: 'Haiti', isoCode: 'ht' },
        { code: 'HUF', nome: 'Hungarian Forint', pais: 'Hungary', isoCode: 'hu' },
        { code: 'IDR', nome: 'Indonesian Rupiah', pais: 'Indonesia', isoCode: 'id' },
        { code: 'ILS', nome: 'Israeli New Shekel', pais: 'Israel', isoCode: 'il' },
        { code: 'IMP', nome: 'Manx Pound', pais: 'Isle of Man', isoCode: 'im' },
        { code: 'INR', nome: 'Indian Rupee', pais: 'India', isoCode: 'in' },
        { code: 'IQD', nome: 'Iraqi Dinar', pais: 'Iraq', isoCode: 'iq' },
        { code: 'IRR', nome: 'Iranian Rial', pais: 'Iran', isoCode: 'ir' },
        { code: 'ISK', nome: 'Icelandic Króna', pais: 'Iceland', isoCode: 'is' },
        { code: 'JEP', nome: 'Jersey Pound', pais: 'Jersey', isoCode: 'je' },
        { code: 'JMD', nome: 'Jamaican Dollar', pais: 'Jamaica', isoCode: 'jm' },
        { code: 'JOD', nome: 'Jordanian Dinar', pais: 'Jordan', isoCode: 'jo' },
        { code: 'JPY', nome: 'Japanese Yen', pais: 'Japan', isoCode: 'jp' },
        { code: 'KES', nome: 'Kenyan Shilling', pais: 'Kenya', isoCode: 'ke' },
        { code: 'KGS', nome: 'Kyrgyzstani Som', pais: 'Kyrgyzstan', isoCode: 'kg' },
        { code: 'KHR', nome: 'Cambodian Riel', pais: 'Cambodia', isoCode: 'kh' },
        { code: 'KID', nome: 'Kiribati Dollar', pais: 'Kiribati', isoCode: 'ki' },
        { code: 'KMF', nome: 'Comorian Franc', pais: 'Comoros', isoCode: 'km' },
        { code: 'KRW', nome: 'South Korean Won', pais: 'South Korea', isoCode: 'kr' },
        { code: 'KWD', nome: 'Kuwaiti Dinar', pais: 'Kuwait', isoCode: 'kw' },
        { code: 'KYD', nome: 'Cayman Islands Dollar', pais: 'Cayman Islands', isoCode: 'ky' },
        { code: 'KZT', nome: 'Kazakhstani Tenge', pais: 'Kazakhstan', isoCode: 'kz' },
        { code: 'LAK', nome: 'Lao Kip', pais: 'Laos', isoCode: 'la' },
        { code: 'LBP', nome: 'Lebanese Pound', pais: 'Lebanon', isoCode: 'lb' },
        { code: 'LKR', nome: 'Sri Lanka Rupee', pais: 'Sri Lanka', isoCode: 'lk' },
        { code: 'LRD', nome: 'Liberian Dollar', pais: 'Liberia', isoCode: 'lr' },
        { code: 'LSL', nome: 'Lesotho Loti', pais: 'Lesotho', isoCode: 'ls' },
        { code: 'LYD', nome: 'Libyan Dinar', pais: 'Libya', isoCode: 'ly' },
        { code: 'MAD', nome: 'Moroccan Dirham', pais: 'Morocco', isoCode: 'ma' },
        { code: 'MDL', nome: 'Moldovan Leu', pais: 'Moldova', isoCode: 'md' },
        { code: 'MGA', nome: 'Malagasy Ariary', pais: 'Madagascar', isoCode: 'mg' },
        { code: 'MKD', nome: 'Macedonian Denar', pais: 'North Macedonia', isoCode: 'mk' },
        { code: 'MMK', nome: 'Burmese Kyat', pais: 'Myanmar', isoCode: 'mm' },
        { code: 'MNT', nome: 'Mongolian Tögrög', pais: 'Mongolia', isoCode: 'mn' },
        { code: 'MOP', nome: 'Macanese Pataca', pais: 'Macau', isoCode: 'mo' },
        { code: 'MRU', nome: 'Mauritanian Ouguiya', pais: 'Mauritania', isoCode: 'mr' },
        { code: 'MUR', nome: 'Mauritian Rupee', pais: 'Mauritius', isoCode: 'mu' },
        { code: 'MVR', nome: 'Maldivian Rufiyaa', pais: 'Maldives', isoCode: 'mv' },
        { code: 'MWK', nome: 'Malawian Kwacha', pais: 'Malawi', isoCode: 'mw' },
        { code: 'MXN', nome: 'Mexican Peso', pais: 'Mexico', isoCode: 'mx' },
        { code: 'MYR', nome: 'Malaysian Ringgit', pais: 'Malaysia', isoCode: 'my' },
        { code: 'MZN', nome: 'Mozambican Metical', pais: 'Mozambique', isoCode: 'mz' },
        { code: 'NAD', nome: 'Namibian Dollar', pais: 'Namibia', isoCode: 'na' },
        { code: 'NGN', nome: 'Nigerian Naira', pais: 'Nigeria', isoCode: 'ng' },
        { code: 'NIO', nome: 'Nicaraguan Córdoba', pais: 'Nicaragua', isoCode: 'ni' },
        { code: 'NOK', nome: 'Norwegian Krone', pais: 'Norway', isoCode: 'no' },
        { code: 'NPR', nome: 'Nepalese Rupee', pais: 'Nepal', isoCode: 'np' },
        { code: 'NZD', nome: 'New Zealand Dollar', pais: 'New Zealand', isoCode: 'nz' },
        { code: 'OMR', nome: 'Omani Rial', pais: 'Oman', isoCode: 'om' },
        { code: 'PAB', nome: 'Panamanian Balboa', pais: 'Panama', isoCode: 'pa' },
        { code: 'PEN', nome: 'Peruvian Sol', pais: 'Peru', isoCode: 'pe' },
        { code: 'PGK', nome: 'Papua New Guinean Kina', pais: 'Papua New Guinea', isoCode: 'pg' },
        { code: 'PHP', nome: 'Philippine Peso', pais: 'Philippines', isoCode: 'ph' },
        { code: 'PKR', nome: 'Pakistani Rupee', pais: 'Pakistan', isoCode: 'pk' },
        { code: 'PLN', nome: 'Polish Złoty', pais: 'Poland', isoCode: 'pl' },
        { code: 'PYG', nome: 'Paraguayan Guaraní', pais: 'Paraguay', isoCode: 'py' },
        { code: 'QAR', nome: 'Qatari Riyal', pais: 'Qatar', isoCode: 'qa' },
        { code: 'RON', nome: 'Romanian Leu', pais: 'Romania', isoCode: 'ro' },
        { code: 'RSD', nome: 'Serbian Dinar', pais: 'Serbia', isoCode: 'rs' },
        { code: 'RUB', nome: 'Russian Ruble', pais: 'Russia', isoCode: 'ru' },
        { code: 'RWF', nome: 'Rwandan Franc', pais: 'Rwanda', isoCode: 'rw' },
        { code: 'SAR', nome: 'Saudi Riyal', pais: 'Saudi Arabia', isoCode: 'sa' },
        { code: 'SBD', nome: 'Solomon Islands Dollar', pais: 'Solomon Islands', isoCode: 'sb' },
        { code: 'SCR', nome: 'Seychellois Rupee', pais: 'Seychelles', isoCode: 'sc' },
        { code: 'SDG', nome: 'Sudanese Pound', pais: 'Sudan', isoCode: 'sd' },
        { code: 'SEK', nome: 'Swedish Krona', pais: 'Sweden', isoCode: 'se' },
        { code: 'SGD', nome: 'Singapore Dollar', pais: 'Singapore', isoCode: 'sg' },
        { code: 'SHP', nome: 'Saint Helena Pound', pais: 'Saint Helena', isoCode: 'sh' },
        { code: 'SLE', nome: 'Sierra Leonean Leone', pais: 'Sierra Leone', isoCode: 'sl' },
        { code: 'SOS', nome: 'Somali Shilling', pais: 'Somalia', isoCode: 'so' },
        { code: 'SRD', nome: 'Surinamese Dollar', pais: 'Suriname', isoCode: 'sr' },
        { code: 'SSP', nome: 'South Sudanese Pound', pais: 'South Sudan', isoCode: 'ss' },
        { code: 'STN', nome: 'São Tomé and Príncipe Dobra', pais: 'São Tomé and Príncipe', isoCode: 'st' },
        { code: 'SYP', nome: 'Syrian Pound', pais: 'Syria', isoCode: 'sy' },
        { code: 'SZL', nome: 'Eswatini Lilangeni', pais: 'Eswatini', isoCode: 'sz' },
        { code: 'THB', nome: 'Thai Baht', pais: 'Thailand', isoCode: 'th' },
        { code: 'TJS', nome: 'Tajikistani Somoni', pais: 'Tajikistan', isoCode: 'tj' },
        { code: 'TMT', nome: 'Turkmenistan Manat', pais: 'Turkmenistan', isoCode: 'tm' },
        { code: 'TND', nome: 'Tunisian Dinar', pais: 'Tunisia', isoCode: 'tn' },
        { code: 'TOP', nome: 'Tongan Pa\´anga', pais: 'Tonga', isoCode: 'to' },
        { code: 'TRY', nome: 'Turkish Lira', pais: 'Turkey', isoCode: 'tr' },
        { code: 'TTD', nome: 'Trinidad and Tobago Dollar', pais: 'Trinidad and Tobago', isoCode: 'tt' },
        { code: 'TVD', nome: 'Tuvaluan Dollar', pais: 'Tuvalu', isoCode: 'tv' },
        { code: 'TWD', nome: 'New Taiwan Dollar', pais: 'Taiwan', isoCode: 'tw' },
        { code: 'TZS', nome: 'Tanzanian Shilling', pais: 'Tanzania', isoCode: 'tz' },
        { code: 'UAH', nome: 'Ukrainian Hryvnia', pais: 'Ukraine', isoCode: 'ua' },
        { code: 'UGX', nome: 'Ugandan Shilling', pais: 'Uganda', isoCode: 'ug' },
        { code: 'USD', nome: 'United States Dollar', pais: 'United States', isoCode: 'us' },
        { code: 'UYU', nome: 'Uruguayan Peso', pais: 'Uruguay', isoCode: 'uy' },
        { code: 'UZS', nome: 'Uzbekistani So\'m', pais: 'Uzbekistan', isoCode: 'uz' },
        { code: 'VES', nome: 'Venezuelan Bolívar Soberano', pais: 'Venezuela', isoCode: 've' },
        { code: 'VND', nome: 'Vietnamese Đồng', pais: 'Vietnam', isoCode: 'vn' },
        { code: 'VUV', nome: 'Vanuatu Vatu', pais: 'Vanuatu', isoCode: 'vu' },
        { code: 'WST', nome: 'Samoan Tālā', pais: 'Samoa', isoCode: 'ws' },
        { code: 'YER', nome: 'Yemeni Rial', pais: 'Yemen', isoCode: 'ye' },
        { code: 'ZAR', nome: 'South African Rand', pais: 'South Africa', isoCode: 'za' },
        { code: 'ZMW', nome: 'Zambian Kwacha', pais: 'Zambia', isoCode: 'zm' },
        { code: 'ZWL', nome: 'Zimbabwean Dollar', pais: 'Zimbabwe', isoCode: 'zw' }
    ];

    constructor(private http: HttpClient) { }
    getCountries() {
        return this.currencies;
    }

    getBandeiraPorCodigoISO(code: string): Observable<any> {
        const url = `https://flagcdn.com/256x192/${code}.png`;
        return this.http.get(url);
    }
}
